# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: O:/ENGS31/MorseCode_VGA/MorseCode_VGA.srcs/sources_1/ip/ascii_memory/ascii_memory.xci
# IP: The module: 'ascii_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ENGS31/MorseCode_VGA/MorseCode_VGA.gen/sources_1/ip/ascii_memory/ascii_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascii_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: O:/ENGS31/MorseCode_VGA/MorseCode_VGA.srcs/sources_1/ip/ascii_memory/ascii_memory.xci
# IP: The module: 'ascii_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/ENGS31/MorseCode_VGA/MorseCode_VGA.gen/sources_1/ip/ascii_memory/ascii_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascii_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
